services:
  gwyneth:
    build: ./dockerfiles/gwyneth/.
    volumes:
      - ./etc/gwyneth.yaml:/app/gwyneth.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8001:80"
  db:
    image: mysql:8.0.36-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=gwyneth
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gwyneth
    volumes:
      - ./var/mysql:/var/lib/mysql:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: mysql
    restart: always
    stop_grace_period: 1m
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./etc/gwyneth_swagger.yml:/usr/share/nginx/html/gwyneth.yml
    environment:
      API_URL: gwyneth.yml
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./etc/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./etc/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - swagger
      - gwyneth
